//! The packages in a `Cargo.lock`.

use crate::toml;

/// One locked package.
#[derive(Debug, Clone, Default, PartialEq, Eq, PartialOrd, Ord)]
pub struct Package {
    /// The crate's name.
    pub name: String,
    /// The exact version.
    pub version: String,
    /// Where it comes from, or `None` for a workspace member or path
    /// dependency.
    pub source: Option<String>,
}

/// Every `[[package]]` entry in `lock`, in file order. Lines outside those
/// entries, such as a `[[patch.unused]]` table, are ignored.
pub fn packages(lock: &str) -> Vec<Package> {
    let mut found = Vec::new();
    let mut current: Option<Package> = None;
    for line in lock.lines() {
        if line.starts_with('[') {
            found.extend(current.take());
            current = (line == "[[package]]").then(Package::default);
        } else if let Some(package) = current.as_mut() {
            if let Some(name) = toml::value(line, "name") {
                name.clone_into(&mut package.name);
            } else if let Some(version) = toml::value(line, "version") {
                version.clone_into(&mut package.version);
            } else if let Some(source) = toml::value(line, "source") {
                package.source = Some(source.to_owned());
            }
        }
    }
    found.extend(current);
    found
}

#[cfg(test)]
mod tests {
    use super::{Package, packages};

    #[test]
    fn reads_every_package_with_its_version_and_source() {
        let lock = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "gunmetal-core"
version = "0.0.0"
dependencies = [
 "proptest",
]

[[package]]
name = "rand"
version = "0.9.5"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "6db2770f06117d490610c7488547d543617b21bfa07796d7a12f6f1bd53850d1"
dependencies = [
 "rand_chacha",
 "rand_core 0.9.5",
]

[[patch.unused]]
name = "unused-patch"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
"#;
        assert_eq!(
            packages(lock),
            [
                Package {
                    name: "gunmetal-core".to_owned(),
                    version: "0.0.0".to_owned(),
                    source: None,
                },
                Package {
                    name: "rand".to_owned(),
                    version: "0.9.5".to_owned(),
                    source: Some(
                        "registry+https://github.com/rust-lang/crates.io-index".to_owned()
                    ),
                },
            ]
        );
    }

    #[test]
    fn reads_nothing_from_a_file_without_packages() {
        assert_eq!(packages("version = 4\n"), []);
    }
}
