//! `xtask wasm-types`: the committed TypeScript declarations of the
//! WebAssembly facade are the ones its mirror types generate.
//!
//! Types cross from Rust to TypeScript by generation, never by hand
//! (record 12, decision 13). Each module of `gunmetal-wasm` lists the
//! declarations `tsify` derives from its mirror types, and each module has
//! one file under [`TYPES`], which the web client imports. This check
//! builds every file's text from those lists and fails when a committed
//! file differs, is missing, or is one that no module generates. A change
//! to a mirror type therefore shows in review as a change to its
//! declaration, and a mirror changed without its file fails the gate.
//!
//! The check writes nothing. `wasm-types print <file>` prints the generated
//! text of one file, to be written to its place:
//!
//! ```text
//! cargo run --locked -q -p xtask -- wasm-types print links.d.ts \
//!   >crates/gunmetal-wasm/types/links.d.ts
//! ```

use crate::tree::Tree;

/// Where the committed declarations live, from the repository root.
pub const TYPES: &str = "crates/gunmetal-wasm/types";

/// One declaration file: its name in [`TYPES`], and its whole text.
pub type File = (String, String);

/// Something `wasm-types` found wrong.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Finding {
    /// A file the mirror types generate is not committed.
    Missing {
        /// Its path from the repository root.
        path: String,
    },
    /// A committed file differs from the one the mirror types generate.
    Drift {
        /// Its path from the repository root.
        path: String,
    },
    /// A committed file that no module of the facade generates.
    Stray {
        /// Its path from the repository root.
        path: String,
    },
}

/// The files the facade's mirror types generate, sorted by name: one for
/// each module of `gunmetal-wasm` that declares mirror types.
pub fn generated() -> Vec<File> {
    vec![
        file("gain", &gunmetal_wasm::gain::DECLARATIONS),
        file("links", &gunmetal_wasm::links::DECLARATIONS),
        file("lyrics", &gunmetal_wasm::lyrics::DECLARATIONS),
        file("player", &gunmetal_wasm::player::DECLARATIONS),
        file("queue", &gunmetal_wasm::queue::DECLARATIONS),
        file("shuffle", &gunmetal_wasm::shuffle::DECLARATIONS),
        file("text", &gunmetal_wasm::text::DECLARATIONS),
    ]
}

/// The generated text of the file `name`, or `None` when no module
/// generates a file of that name.
pub fn text(name: &str) -> Option<String> {
    generated()
        .into_iter()
        .find_map(|(listed, text)| (listed == name).then_some(text))
}

/// The file of the facade module `module`, which declares `declarations`:
/// a header that says where the file comes from, then each declaration,
/// a blank line apart.
fn file(module: &str, declarations: &[&str]) -> File {
    (
        format!("{module}.d.ts"),
        format!(
            "// Generated from crates/gunmetal-wasm/src/{module}.rs. Do not edit this file:\n\
             // change the mirror type, then write the output of\n\
             // `cargo run --locked -q -p xtask -- wasm-types print {module}.d.ts` here.\n\
             \n\
             {}\n",
            declarations.join("\n\n")
        ),
    )
}

/// Compares the files beneath [`TYPES`] in `tree` with the `generated`
/// ones.
pub fn check(tree: &dyn Tree, generated: &[File]) -> Vec<Finding> {
    let mut findings = Vec::new();
    for (name, text) in generated {
        let path = format!("{TYPES}/{name}");
        match tree.read(&path) {
            None => findings.push(Finding::Missing { path }),
            Some(committed) if committed != *text => findings.push(Finding::Drift { path }),
            Some(_) => {}
        }
    }
    for name in tree.files(TYPES) {
        if !generated.iter().any(|(listed, _)| *listed == name) {
            findings.push(Finding::Stray {
                path: format!("{TYPES}/{name}"),
            });
        }
    }
    findings
}

#[cfg(test)]
mod tests {
    use super::{File, Finding, check, file, text};
    use crate::ROOT;
    use crate::tree::memory::Memory;
    use crate::tree::{Disk, Tree};

    /// The committed path of the links module's file.
    const LINKS: &str = "crates/gunmetal-wasm/types/links.d.ts";

    /// The declaration of a mirror with two fields.
    const TWO_FIELDS: &str = "export interface Link {\n    href: string;\n    host: string;\n}\n";

    /// One generated file named `name` that holds `text`.
    fn generated(name: &str, text: &str) -> [File; 1] {
        [(name.to_owned(), text.to_owned())]
    }

    #[test]
    fn committed_files_that_equal_the_generated_ones_pass() {
        let tree = Memory::default()
            .with(LINKS, TWO_FIELDS)
            .with("crates/gunmetal-wasm/src/links.rs", "pub struct Link;\n")
            .with("crates/gunmetal-wasm-extra/types/other.d.ts", "");
        assert_eq!(check(&tree, &generated("links.d.ts", TWO_FIELDS)), []);
    }

    #[test]
    fn a_mirror_with_a_field_removed_fails_as_drift() {
        // The committed copy still declares `host`, which the mirror lost.
        let tree = Memory::default().with(LINKS, TWO_FIELDS);
        let one_field = "export interface Link {\n    href: string;\n}\n";
        assert_eq!(
            check(&tree, &generated("links.d.ts", one_field)),
            [Finding::Drift {
                path: LINKS.to_owned()
            }]
        );
    }

    #[test]
    fn a_generated_file_that_is_not_committed_fails_as_missing() {
        let tree = Memory::default().with(LINKS, TWO_FIELDS);
        let both = [
            (
                "ids.d.ts".to_owned(),
                "export type Id = string;\n".to_owned(),
            ),
            ("links.d.ts".to_owned(), TWO_FIELDS.to_owned()),
        ];
        assert_eq!(
            check(&tree, &both),
            [Finding::Missing {
                path: "crates/gunmetal-wasm/types/ids.d.ts".to_owned()
            }]
        );
    }

    #[test]
    fn a_committed_file_that_no_module_generates_fails_as_stray() {
        let tree = Memory::default()
            .with(LINKS, TWO_FIELDS)
            .with("crates/gunmetal-wasm/types/old.d.ts", TWO_FIELDS)
            .with("crates/gunmetal-wasm/types/nested/links.d.ts", TWO_FIELDS);
        assert_eq!(
            check(&tree, &generated("links.d.ts", TWO_FIELDS)),
            [
                Finding::Stray {
                    path: "crates/gunmetal-wasm/types/nested/links.d.ts".to_owned()
                },
                Finding::Stray {
                    path: "crates/gunmetal-wasm/types/old.d.ts".to_owned()
                },
            ]
        );
    }

    #[test]
    fn a_module_s_file_is_a_header_then_its_declarations_a_blank_line_apart() {
        assert_eq!(
            file(
                "links",
                &["export type A = string;", "export type B = number;"]
            ),
            (
                "links.d.ts".to_owned(),
                "// Generated from crates/gunmetal-wasm/src/links.rs. Do not edit this file:\n\
                 // change the mirror type, then write the output of\n\
                 // `cargo run --locked -q -p xtask -- wasm-types print links.d.ts` here.\n\
                 \n\
                 export type A = string;\n\
                 \n\
                 export type B = number;\n"
                    .to_owned()
            )
        );
    }

    #[test]
    fn the_text_of_a_file_is_found_by_its_whole_name_only() {
        let committed = Disk::new(ROOT).read(LINKS);
        assert!(
            committed
                .as_ref()
                .is_some_and(|text| text.contains("export interface Link {")),
            "the links declarations are committed: {committed:?}"
        );
        assert_eq!(text("links.d.ts"), committed);
        assert_eq!(text("links"), None);
        assert_eq!(text("links.d.ts.orig"), None);
        assert_eq!(text(""), None);
    }
}
