// Generated from crates/gunmetal-wasm/src/gain.rs. Do not edit this file:
// change the mirror type, then write the output of
// `cargo run --locked -q -p xtask -- wasm-types print gain.d.ts` here.

/**
 * How the player chooses between track and album gain.
 */
export type Mode = "Auto" | "Track" | "Album" | "Off";

/**
 * Which scheme the file's tags were written against.
 */
export type Scheme = "ReplayGain" | "R128";

/**
 * Where the chosen gain came from.
 */
export type Source = "TaggedTrack" | "TaggedAlbum" | "Measured" | "Estimated" | "Off";

/**
 * Which safety clamp changed the gain.
 */
export type Clamp = "None" | "Range" | "NoPeak" | "Peak";

/**
 * Everything the decision needs about one track. Gains are dB; peaks are a
 * ratio of full scale; measured loudness is LUFS. A finite value outside
 * the core's range, or a non-finite one, is [`GainOutcome::Unusable`].
 */
export interface GainInput {
    /**
     * `ReplayGain` or R128 track gain, in dB.
     */
    track_gain: number | undefined;
    /**
     * `ReplayGain` or R128 album gain, in dB.
     */
    album_gain: number | undefined;
    /**
     * Track peak as a ratio of full scale.
     */
    track_peak: number | undefined;
    /**
     * Album peak as a ratio of full scale.
     */
    album_peak: number | undefined;
    /**
     * Which reference the tags were written against.
     */
    scheme: Scheme;
    /**
     * Opus identification-header output gain. Always added.
     */
    opus_header: number | undefined;
    /**
     * Integrated loudness from a measurement pass, when tags are missing.
     */
    measured: number | undefined;
    /**
     * The previous From-lane item is the same album.
     */
    prev_same_album: boolean;
    /**
     * The next From-lane item is the same album.
     */
    next_same_album: boolean;
}

/**
 * The gain the player applies, where it came from, which clamp ran, and
 * the linear factor to set on a gain node.
 */
export interface GainDecision {
    /**
     * The gain to apply, after every clamp, in dB.
     */
    applied_db: number;
    /**
     * Ten to the power of `applied_db` over twenty: the Web Audio factor.
     */
    factor: number;
    /**
     * Where the pre-clamp gain came from.
     */
    source: Source;
    /**
     * The last clamp that changed the value, or `None`.
     */
    clamp: Clamp;
}

/**
 * What reading a gain request gave.
 */
export type GainOutcome = { Decision: GainDecision } | "Unusable";
