// Generated from crates/gunmetal-wasm/src/links.rs. Do not edit this file:
// change the mirror type, then write the output of
// `cargo run --locked -q -p xtask -- wasm-types print links.d.ts` here.

/**
 * A link that may be shown as a link and opened.
 */
export interface Link {
    /**
     * The URL to open, rewritten so that every URL parser reads the same host from it.
     */
    href: string;
    /**
     * The host to show before the link is opened.
     */
    host: string;
}

/**
 * Why a URL must be shown as plain text instead of a link.
 */
export type LinkError = "NotAbsolute" | "NotHttps" | "Credentials" | "NoHost" | "BadHost" | "BadPort";

/**
 * What reading a URL gave: a link, or the reason it stays plain text.
 */
export type LinkOutcome = { Link: Link } | { PlainText: LinkError };
