// Generated from crates/gunmetal-wasm/src/lyrics.rs. Do not edit this file:
// change the mirror type, then write the output of
// `cargo run --locked -q -p xtask -- wasm-types print lyrics.d.ts` here.

/**
 * A line with a time.
 */
export interface Line {
    /**
     * When the line starts, in milliseconds.
     */
    at: number;
    /**
     * The line.
     */
    text: string;
}

/**
 * A word with a time.
 */
export interface Word {
    /**
     * When the word starts, in milliseconds.
     */
    at: number;
    /**
     * The word.
     */
    text: string;
}

/**
 * A line whose words have a time each.
 */
export interface WordLine {
    /**
     * When the line starts, in milliseconds.
     */
    at: number;
    /**
     * The words in order.
     */
    words: Word[];
}

/**
 * Lyrics, in the order they are sung.
 */
export type Lyrics = { Plain: string[] } | { Lines: Line[] } | { Words: WordLine[] };

/**
 * The line, and the word in it, that a player is at.
 */
export interface Cursor {
    /**
     * The index of the line in the lyrics.
     */
    line: number;
    /**
     * The index of the word in that line, or omitted before its first word
     * and in lyrics without word times.
     */
    word: number | undefined;
}

/**
 * What [`lyric_position`] found.
 */
export type LyricPosition = { At: Cursor } | "None";
