// Generated from crates/gunmetal-wasm/src/player.rs. Do not edit this file:
// change the mirror type, then write the output of
// `cargo run --locked -q -p xtask -- wasm-types print player.d.ts` here.

/**
 * What the player is doing right now.
 */
export type State = "Idle" | "Loading" | "Playing" | "Paused" | "Buffering" | "Stalled" | "ItemEnded" | "EndOfQueue" | "Error" | "Stopped";

/**
 * An input the machine accepts.
 */
export type Event = "Play" | "FirstAudioOrFirstFrame" | "CannotStart" | "Pause" | "BufferRanDry" | "BufferRefilled" | "NoProgress" | "Recovered" | "GaveUp" | "EndOfItem" | "NextItem" | "NothingNext" | "StartRadio" | "Retry" | "Skip" | "StoppedByOwner" | "DeviceRevoked";

/**
 * `playerNext` was called with a pair the diagram has no arrow for.
 */
export interface Illegal {
    /**
     * The state that received the event.
     */
    state: State;
    /**
     * The event that has no arrow from that state.
     */
    event: Event;
}

/**
 * The next state, or the pair that is not an arrow.
 */
export type PlayerStep = { State: State } | { Illegal: Illegal };
