// Generated from crates/gunmetal-wasm/src/queue.rs. Do not edit this file:
// change the mirror type, then write the output of
// `cargo run --locked -q -p xtask -- wasm-types print queue.d.ts` here.

/**
 * A named listening context.
 */
export type ListenContext = "Music";

/**
 * A lane a person can put entries into.
 */
export type QueueLane = "UpNext" | "From";

/**
 * What happens when an item ends.
 */
export type RepeatMode = "Off" | "One" | "All";

/**
 * When playback stops of its own accord.
 */
export type StopAfterMode = "Off" | "Item" | "Source";

/**
 * Where a moved entry goes.
 */
export type MoveTo = { Before: string } | { End: QueueLane };

/**
 * One queued item. `id` is 32 lower-case hex digits; `item` and `source`
 * are canonical public identifiers.
 */
export interface QueueEntry {
    /**
     * Names this entry within the queue.
     */
    id: string;
    /**
     * The item to play.
     */
    item: string;
    /**
     * Where the item was chosen from.
     */
    source: string;
}

/**
 * The entry playing now, and the lane it was taken from.
 */
export interface Playing {
    /**
     * The entry.
     */
    entry: QueueEntry;
    /**
     * Where it came from.
     */
    lane: QueueLane;
}

/**
 * The From lane.
 */
export interface FromLaneMirror {
    /**
     * What the last Play played, or omitted until the first Play.
     */
    source: string | undefined;
    /**
     * The lane's entries before the current one.
     */
    before: QueueEntry[];
    /**
     * The lane's entries still to play.
     */
    upcoming: QueueEntry[];
}

/**
 * One profile's queue in one listening context.
 */
export interface QueueDoc {
    /**
     * How many operations have changed the document.
     */
    version: number;
    /**
     * The listening context this queue belongs to.
     */
    context: ListenContext;
    /**
     * The entry playing now.
     */
    current: Playing | undefined;
    /**
     * How far into the current entry, in milliseconds.
     */
    position_ms: number | undefined;
    /**
     * The person's picks, in the order they play.
     */
    up_next: QueueEntry[];
    /**
     * Where in Up next the next "play next" goes.
     */
    cursor: number;
    /**
     * The album, artist or playlist being played.
     */
    from: FromLaneMirror;
    /**
     * Suggestions for when the From lane ends.
     */
    continue_with: QueueEntry[];
    /**
     * What happens when an item ends.
     */
    repeat: RepeatMode;
    /**
     * When playback stops of its own accord.
     */
    stop_after: StopAfterMode;
    /**
     * The session that last issued Play or Resume.
     */
    player: string | undefined;
}

/**
 * An item an operation adds.
 */
export interface NewQueueEntry {
    /**
     * The new entry's ID, 32 lower-case hex digits.
     */
    id: string;
    /**
     * The item to play, a canonical public identifier.
     */
    item: string;
}

/**
 * One change to a queue.
 */
export type QueueOp = { Play: { source: string; items: NewQueueEntry[]; start: number; by: string } } | { PlayNext: { source: string; items: NewQueueEntry[] } } | { Add: { source: string; items: NewQueueEntry[] } } | { PlayLast: { source: string; items: NewQueueEntry[] } } | { Move: { entry: string; to: MoveTo } } | { Remove: string[] } | "ClearUpNext" | "Clear" | { Finished: string } | { Skip: string } | { Resume: { by: string } } | { SetRepeat: RepeatMode } | { SetStopAfter: StopAfterMode };

/**
 * Why an operation was refused, or why a value could not be converted.
 */
export type QueueError = { Stale: { current: number } } | "VersionExhausted" | "NoItems" | { StartOutOfRange: { start: number; items: number } } | { DuplicateEntry: { entry: string } } | { UnknownEntry: { entry: string } } | { NotCurrent: { entry: string } } | "NothingToPlay" | "NotPlayer" | "Unusable";

/**
 * What applying an operation gave.
 */
export type ApplyOutcome = { Queue: QueueDoc } | { Error: QueueError };

/**
 * An operation the client has applied to its own copy and sent.
 */
export interface Pending {
    /**
     * The version the operation was built on.
     */
    based_on: number;
    /**
     * The operation.
     */
    op: QueueOp;
}

/**
 * A pending operation that no longer fits the server's queue.
 */
export interface DroppedOp {
    /**
     * The operation.
     */
    op: QueueOp;
    /**
     * Why it no longer fits.
     */
    reason: QueueError;
}

/**
 * The client's queue after a rebase.
 */
export interface RebasedQueue {
    /**
     * The server's queue with the pending operations that still fit applied.
     */
    queue: QueueDoc;
    /**
     * Those operations, each built on the version before it.
     */
    pending: Pending[];
    /**
     * The operations that no longer fit.
     */
    dropped: DroppedOp[];
}

/**
 * What rebasing pending operations gave.
 */
export type RebaseOutcome = { Rebased: RebasedQueue } | "Unusable";

/**
 * A rebase request: the operations the server has not acknowledged, and
 * the server's queue.
 */
export interface RebaseRequest {
    /**
     * The operations the client has sent, in order.
     */
    pending: Pending[];
    /**
     * The server's queue.
     */
    server: QueueDoc;
}

/**
 * An apply request.
 */
export interface ApplyRequest {
    /**
     * The queue to change.
     */
    queue: QueueDoc;
    /**
     * The version the operation was built on.
     */
    based_on: number;
    /**
     * The operation.
     */
    op: QueueOp;
}
