// Generated from crates/gunmetal-wasm/src/shuffle.rs. Do not edit this file:
// change the mirror type, then write the output of
// `cargo run --locked -q -p xtask -- wasm-types print shuffle.d.ts` here.

/**
 * How the From lane is ordered.
 */
export type Mode = "Off" | "Random" | "SpreadOut";

/**
 * One From-lane item, named only by the artist and album keys spread-out
 * needs.
 */
export interface ShuffleItem {
    /**
     * The caller-chosen artist grouping key.
     */
    artist: number;
    /**
     * The caller-chosen album grouping key.
     */
    album: number;
}

/**
 * A last-played time of one artist or album, as milliseconds since the
 * Unix epoch.
 */
export interface RecentPlay {
    /**
     * The grouping key.
     */
    key: number;
    /**
     * When it was last played, in milliseconds since the Unix epoch.
     */
    at: number;
}

/**
 * Last-played times of artists and albums, used only by `SpreadOut`.
 */
export interface RecentPlays {
    /**
     * Artists, each with the later time kept when the same key is listed twice.
     */
    artists: RecentPlay[];
    /**
     * Albums, each with the later time kept when the same key is listed twice.
     */
    albums: RecentPlay[];
}

/**
 * Everything [`shuffle_order`] needs.
 */
export interface ShuffleRequest {
    /**
     * The From-lane items, in source order.
     */
    items: ShuffleItem[];
    /**
     * How to order them.
     */
    mode: Mode;
    /**
     * The seed; the same seed and items yield the same order on every device.
     */
    seed: number;
    /**
     * Last-played times, used only by `SpreadOut`.
     */
    recent: RecentPlays;
}

/**
 * The permutation [`shuffle_order`] returns: indices into the request's
 * items.
 */
export interface ShuffleOrder {
    /**
     * Each index is into the request's `items`.
     */
    indices: number[];
}

/**
 * What reading a shuffle request gave.
 */
export type ShuffleOutcome = { Order: ShuffleOrder } | "UnusableTime";
