// Generated from crates/gunmetal-wasm/src/text.rs. Do not edit this file:
// change the mirror type, then write the output of
// `cargo run --locked -q -p xtask -- wasm-types print text.d.ts` here.

/**
 * Whether a field may hold more than one line.
 */
export type Lines = "Single" | "Multi";

/**
 * Text that is safe to store and to show as text.
 */
export interface NormalisedText {
    /**
     * The text.
     */
    value: string;
    /**
     * Whether characters past the cap were dropped, so that the value is a prefix of the whole text.
     */
    truncated: boolean;
    /**
     * Whether the input held octets that were not UTF-8, now replaced with U+FFFD.
     */
    replaced: boolean;
}
